"""add batch_id columns

Revision ID: 18e671e00236
Revises: 
Create Date: 2025-05-10 14:02:22.240172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18e671e00236'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bins', sa.Column('batch_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_bins_batch_id'), 'bins', ['batch_id'], unique=False)
    op.create_index(op.f('ix_bins_id'), 'bins', ['id'], unique=False)
    op.add_column('routes', sa.Column('batch_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_routes_batch_id'), 'routes', ['batch_id'], unique=False)
    op.create_index(op.f('ix_routes_id'), 'routes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routes_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_batch_id'), table_name='routes')
    op.drop_column('routes', 'batch_id')
    op.drop_index(op.f('ix_bins_id'), table_name='bins')
    op.drop_index(op.f('ix_bins_batch_id'), table_name='bins')
    op.drop_column('bins', 'batch_id')
    # ### end Alembic commands ###
