"""add edges column to routes

Revision ID: 48004a2ddfb4
Revises: 809125ecc841
Create Date: 2025-05-10 14:17:47.688660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48004a2ddfb4'
down_revision: Union[str, None] = '809125ecc841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('batch_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_routes_batch_id'), 'routes', ['batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routes_batch_id'), table_name='routes')
    op.drop_column('routes', 'batch_id')
    # ### end Alembic commands ###
