"""add edges column to routes

Revision ID: 809125ecc841
Revises: 18e671e00236
Create Date: 2025-05-10 14:16:46.991854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '809125ecc841'
down_revision: Union[str, None] = '18e671e00236'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('edges', sa.JSON(), nullable=True))
    op.drop_index('ix_routes_batch_id', table_name='routes')
    op.drop_column('routes', 'batch_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('batch_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_routes_batch_id', 'routes', ['batch_id'], unique=False)
    op.drop_column('routes', 'edges')
    # ### end Alembic commands ###
